### ISSUE TITLE
LiveReload doesn't happen on Firefox

### ISSUE THREAD

**Issue by ronjouch** [cortesi/devd#23]
... and instead logs this error message in the console:

```
The connection to ws://devd.io:8000/.devd.livereload was interrupted while the page was loading.
```

I did start a simple `devd -ol .`, using devd 0.2, from a folder hosting some static pages, and modified the css background to red. Expected result: background turns red. Actual: nothing, except the error message in the log.

May be related to [this stackoverflow post](http://stackoverflow.com/questions/14140414/websocket-interrupted-while-page-is-loading-on-firefox-for-socket-io) and [bugzilla#712329](https://bugzilla.mozilla.org/show_bug.cgi?id=712329)?

**Comment by cortesi** [comment]
Hey. I've just committed a partial fix for this. Livereload of CSS now works in Firefox, but due to the bug you linked we can't silence the websocket error on console. It's a shame, but there you have it. I'll think about the best way to tackle this - it may be that moving to long-polling instead of websockets is the way to go.

**Comment by ronjouch** [comment]
Fantastic, thanks for the fast fix and the 0.3 release :+1: ! I confirm it now works both for html and css, and I confirm the error message mentioned in #24 still shows up, but I can live with that :) . Thanks again!
